# Generated by Django 2.2.4 on 2020-07-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.TextField(default='Besteva'),
            preserve_default=False,
        ),
    ]
