# Generated by Django 2.2.4 on 2020-07-25 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_books', '0002_book_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='users_who_like',
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fav_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_book', to='favorite_books.Book')),
                ('fav_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_user', to='favorite_books.User')),
            ],
        ),
    ]
